#!/usr/bin/env bash
# session-end-vault.sh — Safety net: writes minimal session log on exit
# If /end was used, this is a no-op (marker file exists).
# If /end was NOT used, writes a bare-bones session log from available data.

set +e

# Hook runtime toggle — skip if disabled via env var
HOOK_NAME="$(basename "${BASH_SOURCE[0]}" .sh)"
if [[ ",${SAIL_DISABLED_HOOKS}," == *",${HOOK_NAME},"* ]]; then
    exit 0
fi

source ~/.claude/hooks/vault-config.sh 2>/dev/null || exit 0

[ "$VAULT_ENABLED" = "1" ] || exit 0
vault_is_available || exit 0

# Check if /end already exported (uses VAULT_EXPORT_MARKER from vault-config.sh)
[ -f "$VAULT_EXPORT_MARKER" ] && exit 0

# Minimal export: just a session breadcrumb
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H%M)  # No colons — NTFS-safe (vault is on Windows NTFS via WSL)
PROJECT=$(basename "$(git rev-parse --show-toplevel 2>/dev/null)" 2>/dev/null)
PROJECT=${PROJECT:-unknown-project}  # Avoid useless pwd fallback
PROJECT=$(vault_sanitize_slug "$PROJECT")
NOTE_PATH="${VAULT_PATH}/Sessions/${DATE}-session-${TIME}.md"

mkdir -p "${VAULT_PATH}/Sessions"

cat > "$NOTE_PATH" << EOF
---
type: session
date: ${DATE}
project: ${PROJECT}
generated_by: safety-net
tags: [session, auto-generated]
---

# Session: ${DATE} ${TIME} — ${PROJECT}

> Auto-generated by session-end hook. Use /end for richer export.

## Project
${PROJECT}

## Notes
Session ended without /end command. No detailed export available.
EOF

exit 0
